pub const DRA_GITHUB_TOKEN: &str = "DRA_GITHUB_TOKEN";
pub const GITHUB_TOKEN: &str = "GITHUB_TOKEN";
pub const GH_TOKEN: &str = "GH_TOKEN";
pub const DRA_DISABLE_GITHUB_AUTHENTICATION: &str = "DRA_DISABLE_GITHUB_AUTHENTICATION";
