pub mod color;
pub mod completion_handler;
pub mod download_handler;
mod github_release;
mod progress_bar;
pub mod result;
pub mod root_command;
mod select_assets;
mod spinner;
pub mod untag_handler;
