FROM rust as builder
WORKDIR /app
COPY Cargo.* ./
COPY src/ src/
RUN cargo install --path .

FROM ubuntu:20.04
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
RUN apt-get update && apt-get install -y xz-utils && rm -rf /var/lib/apt/lists/*
# Add user with no root permissions
RUN useradd -ms /bin/bash tester
COPY --from=builder /usr/local/cargo/bin/dra /usr/local/bin/dra
